name: PHP

on: [pull_request]

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Composer dependencies
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Install Composer dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --no-interaction

  lint:
    name: Lint
    needs: [dependencies]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Composer dependencies
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Build
        run: composer build:lint

      - name: Lint against Laravel code style
        run: composer lint

  test:
    name: Test
    needs: [dependencies, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Composer dependencies
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Setup application
        run: |
          cp .env.testing .env

      - name: Build
        run: composer build:test

      - name: Run tests
        run: composer test:coverage
